- hosts: pomodoro
  become: yes
  tasks:
    - name: Install Python 3 et pip
      apt:
        name:
          - python3
          - python3-pip
        update_cache: yes

    - name: Installer Flask via pip
      pip:
        name: flask

    - name: Cloner le projet pomodoro
      git:
        repo: 'https://github.com/AxelColliaux/pomodoro-CS50x.git'
        dest: /home/azureuser/pomodoro
        update: yes

    - name: S'assurer que le dossier flask_session existe avec les bons droits
      file:
        path: /home/azureuser/pomodoro/app/flask_session
        state: directory
        owner: azureuser
        group: azureuser
        mode: '0700'

    - name: Installer les dépendances Python du projet
      pip:
        requirements: /home/azureuser/pomodoro/app/requirements.txt
      args:
        chdir: /home/azureuser/pomodoro

    - name: Installer le client sqlite3
      apt:
        name: sqlite3
        state: present
        update_cache: yes

    - name: S'assurer que le dossier app existe et appartient à azureuser
      file:
        path: /home/azureuser/pomodoro/app
        state: directory
        owner: azureuser
        group: azureuser
        mode: '0755'

    - name: Supprimer la base SQLite si elle existe (reset complet)
      file:
        path: /home/azureuser/pomodoro/app/pomodoro.db
        state: absent

    - name: Initialiser la base SQLite avec la structure attendue
      become: false
      shell: sqlite3 /home/azureuser/pomodoro/app/pomodoro.db < /home/azureuser/pomodoro/app/init_db.sql
      args:
        executable: /bin/bash
      become_user: azureuser

    - name: Vérifier les droits sur la base SQLite
      file:
        path: /home/azureuser/pomodoro/app/pomodoro.db
        owner: azureuser
        group: azureuser
        mode: '0664'

    - name: Créer le service systemd pour Flask
      copy:
        dest: /etc/systemd/system/flask-pomodoro.service
        content: |
          [Unit]
          Description=Flask Pomodoro Service
          After=network.target

          [Service]
          User=azureuser
          WorkingDirectory=/home/azureuser/pomodoro/app
          Environment="FLASK_APP=app.py" "FLASK_ENV=production"
          ExecStart=/usr/local/bin/flask run --host=0.0.0.0
          Restart=always

          [Install]
          WantedBy=multi-user.target
      notify: Reload systemd

    - name: Activer le service Flask au démarrage
      systemd:
        name: flask-pomodoro
        enabled: yes
        state: started

  handlers:
    - name: Reload systemd
      command: systemctl daemon-reload


